####################
### KEYBINDINGS  ###
####################

$mainMod = SUPER

bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow

bind = $mainMod, RETURN, exec, $terminal
bind = $mainMod, W, killactive,
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, R, exec, $menu
bind = $mainMod, S, exec, $runMenu
bind = $mainMod, T, togglegroup
bind = $mainMod, D, exec, $browser

bind = $mainMod SHIFT, Q, exec, $shutdown
bind = $mainMod SHIFT, R, exec, $reboot
bind = $mainMod SHIFT, S, exec, $sleep

bind = $mainMod, F, fullscreen

bind = $mainMod, H, movefocus, l
bind = $mainMod, L, movefocus, r
bind = $mainMod, K, movefocus, u
bind = $mainMod, J, movefocus, d

bind = $mainMod, U, workspace, 1
bind = $mainMod, I, workspace, 2
bind = $mainMod, O, workspace, 3
bind = $mainMod, P, workspace, 4
bind = $mainMod, bracketleft, workspace, 5
bind = $mainMod SHIFT, U, workspace, 6
bind = $mainMod SHIFT, I, workspace, 7
bind = $mainMod SHIFT, O, workspace, 8
bind = $mainMod SHIFT, P, workspace, 9
bind = $mainMod SHIFT, bracketleft, workspace, 10

bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

bind = $mainMod ALT, right, workspace, e+1
bind = $mainMod alt, left, workspace, e-1

bind = $mainMod ALT, L, resizeactive, 10 0
bind = $mainMod ALT, H, resizeactive, -10 0
bind = $mainMod ALT, K, resizeactive, 0 -10
bind = $mainMod ALT, J, resizeactive, 0 10

bind = $mainMod SHIFT, H, movewindow, l
bind = $mainMod SHIFT, L, movewindow, r
bind = $mainMod SHIFT, K, movewindow, u
bind = $mainMod SHIFT, J, movewindow, d

bind = $mainMod, left, movewindoworgroup, l
bind = $mainMod, right, movewindoworgroup, r
bind = $mainMod, down, movewindoworgroup, d
bind = $mainMod, up, movewindoworgroup, u

bind = $mainMod, TAB, changegroupactive, f
bind = $mainMod SHIFT, TAB, changegroupactive, b

bind = $mainMod, grave, exec, switch=$(hyprctl devices -j | jq -r '.keyboards[] | .active_keymap' | uniq -c | [ $(wc -l) -eq 1 ] && echo "next" || echo "0"); for device in $(hyprctl devices -j | jq -r '.keyboards[] | .name'); do hyprctl switchxkblayout $device $switch; done; activeKeymap=$(hyprctl devices -j | jq -r '.keyboards[0] | .active_keymap'); if [ $switch == "0" ]; then resetStr="(reset)"; else resetStr=""; fi; hyprctl notify -1 1500 0 "$activeKeymap $resetStr";

bind = $mainMod, PRINT, exec, hyprshot -m window -o Screenshots
bind = , PRINT, exec, hyprshot -m output -o Screenshots
bind = $mainMod SHIFT, PRINT, exec, hyprshot -m region -o Screenshots
bind = SHIFT, PRINT, exec, hyprshot -m region --clipboard-only