###################
### MY PROGRAMS ###
###################

$terminal = kitty
$fileManager = nemo
$menu = rofi -show drun
$runMenu = rofi -show run
$browser = zen-browser
$shutdown = systemctl poweroff
$reboot = systemctl reboot
$hibernate = systemctl hibernate
$sleep = systemctl sleep