################
### MONITORS ###
################

monitor=eDP-1,2880x1800@60.00,0x0,2
monitor = , prefered , auto, 2

input {
    sensitivity = 0.6
}

device {
    name=wacom-one-by-wacom-s-pen
    output=eDP-1
}

workspace = 1, monitor:eDP-1
workspace = 2, monitor:eDP-1
workspace = 3, monitor:eDP-1
workspace = 4, monitor:eDP-1
workspace = 5, monitor:eDP-1
workspace = 6, monitor:eDP-1
workspace = 7, monitor:eDP-1
workspace = 8, monitor:eDP-1
workspace = 9, monitor:eDP-1
workspace = 10, monitor:eDP-1