# monet.nvim colorscheme for Kitty
# Based on https://github.com/fynnfluegge/monet.nvim

# The basic colors
foreground              #f2ece6
background              #202636
selection_foreground    #202636
selection_background    #61677f

# Cursor colors
cursor                  #f2ece6
cursor_text_color       #202636

# URL underline color when hovering with mouse
url_color               #deb787

# Kitty window border colors
active_border_color     #5cfff7
inactive_border_color   #51586b
bell_border_color       #ead49a

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #202636
active_tab_background   #a0d2fa
inactive_tab_foreground #f2ece6
inactive_tab_background #1a1f2b
tab_bar_background      #1a1f2b

# Colors for marks (marked text in the terminal)
mark1_foreground #202636
mark1_background #63b1ff
mark2_foreground #202636
mark2_background #a0d2fa
mark3_foreground #202636
mark3_background #5cd5db

# The 16 terminal colors

# black
color0 #918d87
color8 #8288a3

# red
color1  #ed8695
color9  #ed8695

# green
color2  #64e880
color10 #64e880

# yellow
color3  #ead49a
color11 #ead49a

# blue
color4  #a0d2fa
color12 #a0d2fa

# magenta
color5  #51c7fc
color13 #51c7fc

# cyan
color6  #82d5e6
color14 #82d5e6

# white
color7  #f2ece6
color15 #f2ece6