# Main hyprland config
# Sources shared modules + active monitor setup

source = confs/shared/colors.conf
source = confs/shared/programs.conf
source = confs/shared/autostart.conf
source = confs/shared/env.conf
source = confs/shared/look.conf
source = confs/shared/input.conf
source = confs/shared/binds.conf
source = confs/shared/rules.conf
source = confs/active-monitor.conf